{$IFDEF VER80}
  {$DEFINE Delphi1}
{$ENDIF}
{$IFDEF VER90}
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
{$ENDIF}
{$IFDEF VER100}
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
  {$DEFINE Delphi3}
{$ENDIF}
{$IFDEF VER120}
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
  {$DEFINE Delphi3}
  {$DEFINE Delphi4}
{$ENDIF}
{$IFDEF  VER130}
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
  {$DEFINE Delphi3}
  {$DEFINE Delphi4}
  {$DEFINE Delphi5}
{$ENDIF}
{$IFDEF VER140}
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
  {$DEFINE Delphi3}
  {$DEFINE Delphi4}
  {$DEFINE Delphi5}
  {$DEFINE Delphi6}
{$ENDIF}
{$IFDEF VER150}
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
  {$DEFINE Delphi3}
  {$DEFINE Delphi4}
  {$DEFINE Delphi5}
  {$DEFINE Delphi6}
  {$DEFINE Delphi7}
{$ENDIF}
{$IFDEF VER160}
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
  {$DEFINE Delphi3}
  {$DEFINE Delphi4}
  {$DEFINE Delphi5}
  {$DEFINE Delphi6}
  {$DEFINE Delphi7}
  {$DEFINE Delphi8}
{$ENDIF}
{$IFDEF VER170} 
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
  {$DEFINE Delphi3}
  {$DEFINE Delphi4}
  {$DEFINE Delphi5}
  {$DEFINE Delphi6}
  {$DEFINE Delphi7}
  {$DEFINE Delphi8}
  {$DEFINE Delphi2005}
{$ENDIF}
{$IFDEF VER180
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
  {$DEFINE Delphi3}
  {$DEFINE Delphi4}
  {$DEFINE Delphi5}
  {$DEFINE Delphi6}
  {$DEFINE Delphi7}
  {$DEFINE Delphi8}
  {$DEFINE Delphi2005}
  {$DEFINE Delphi2006}
  {$DEFINE Delphi2007}
{$ENDIF}
{$IFDEF VER185}
  {$DEFINE Delphi1}
  {$DEFINE Delphi2}
  {$DEFINE Delphi3}
  {$DEFINE Delphi4}
  {$DEFINE Delphi5}
  {$DEFINE Delphi6}
  {$DEFINE Delphi7}
  {$DEFINE Delphi8}
  {$DEFINE Delphi2005}
  {$DEFINE Delphi2006}
  {$DEFINE Delphi2007}
{$ENDIF}